PKGDIR	?= ../..
L4DIR	?= $(PKGDIR)/../..
PKGNAME := re/util
EXTRA_TARGET += basic_dispatcher   \
  bitmap_cap_alloc   \
  cap                \
  cap_alloc          \
  counting_cap_alloc \
  dataspace_svr      \
  debug              \
  env_ns             \
  event_buffer       \
  event_svr          \
  icu_svr            \
  item_alloc         \
  meta               \
  name_space_svr     \
  object_registry    \
  region_mapping     \
  region_mapping_svr \
  vcon_svr           \
  video/get_view     \
  video/goos_svr     \
  video/goos_fb      \
  event


include $(L4DIR)/mk/include.mk
