PKGDIR          ?= ..
L4DIR           ?= $(PKGDIR)/../..

TARGET                   = ex_clntsrv-server ex_clntsrv-client
SRC_CC_ex_clntsrv-server = server.cc
SRC_CC_ex_clntsrv-client = client.cc

include $(L4DIR)/mk/prog.mk

