PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= libcxx_libc_io
SRC_CC		= io_backend.cc
PC_FILENAME     = cxx_libc_io

include $(L4DIR)/pkg/cxx/lib/Makefile.inc
include $(L4DIR)/mk/lib.mk

$(GENERAL_D_LOC): $(L4DIR)/pkg/cxx/lib/Makefile.inc
