PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

EXTRA_TARGET := \
  server/factory \
  server/lua \
  server/mode \
  server/plugin \
  server/user_state \
  server/view \
  server/view_stack \
  server/input_driver \
  server/input_source \
  server/object \


include $(L4DIR)/mk/include.mk
