PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../..

include $(L4DIR)/mk/Makeconf
-include $(PKGDIR_OBJ)/Makeconf

#ifeq ($(CONFIG_DDE26),y)
TARGET = smc dde26_test ne2k
#endif

include $(L4DIR)/mk/subdir.mk


