#ifndef MK1MF_BUILD"
/* auto-generated by crypto/Makefile for crypto/cversion.c */
#define CFLAGS "gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DTERMIO -fomit-frame-pointer -Wall"
#define PLATFORM "l4-generic32"
#define DATE "2011-10-18"
#endif