PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		:= lib4re_main.a
SRC_CC           = __main.cc
PC_FILENAME     := l4re-main
REQUIRES_LIBS   := l4re
CXXFLAGS        := -fno-exceptions

include $(L4DIR)/mk/lib.mk

