PKGDIR	?= ..
L4DIR	?= $(PKGDIR)/../..
PKGNAME := re
EXTRA_TARGET += \
  cap_alloc \
  console   \
  consts    \
  dataspace \
  debug     \
  env       \
  error_helper \
  event     \
  log       \
  mem_alloc \
  namespace \
  parent    \
  protocols \
  rm        \
  video/colors \
  video/goos \
  video/view

include $(L4DIR)/mk/include.mk
