PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../..

PKGNAME		= sys
EXTRA_TARGET	+= capability kip task factory irq icu semaphore thread vcon \
                   smart_capability scheduler meta typeinfo_svr ipc_gate \
                   __vm ARCH-x86/vm ARCH-amd64/vm ARCH-arm/vm

include $(L4DIR)/mk/include.mk


