PKGDIR	?= ..
L4DIR	?= $(PKGDIR)/../..

# the default is to build the listed directories, provided that they
# contain a Makefile. If you need to change this, uncomment the following
# line and adapt it.
TARGET = aes_linux aes_linux_586 aes_openssl \
	 sha1_linux sha1_ref sha1_oslo sha1_openssl \
	 sha1_linux_new base64 modes pad rsaref2

include $(L4DIR)/mk/subdir.mk
