PKGDIR	= ../../..
L4DIR	?= $(PKGDIR)/../..
EXTRA_TARGET := \
  arith       \
  auto_ptr    \
  avl_tree    \
  avl_set     \
  avl_map     \
  bitmap      \
  dlist       \
  hlist       \
  list        \
  list_alloc  \
  minmax      \
  observer    \
  pair        \
  ref_ptr     \
  slab_alloc  \
  std_alloc   \
  std_ops     \
  std_tmpl    \
  type_traits

include $(L4DIR)/mk/include.mk
