PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../..

TARGET           = inputtst
SRC_C            = main.c
L4_MULTITHREADED = y
MODE_USE_C       = y
DEPENDS_PKGS     = input
REQUIRES_LIBS    = input

include $(L4DIR)/mk/prog.mk
